version: '3.8'

services:
  backend:
    build: ./backend
    network_mode: "host" # 추가
    restart: unless-stopped
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
    working_dir: /app
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # ports: - "8000:8000"  # 삭제 (host 모드에서는 불필요)
    # networks: - rag-network  # 삭제

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - rag-network
    depends_on:
      - backend

networks:
  rag-network:
    driver: bridge

volumes:
  node_modules:
