version: '3.8'

services:
  backend:
    build: ./backend
    network_mode: "host"  # host 네트워크 사용
    restart: unless-stopped
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
    working_dir: /app
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    network_mode: "host"  # host 네트워크 사용
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - backend

# networks 섹션 제거 (host 모드에서는 불필요)
